### ISSUE TITLE
Parse owner and repository from package.json

### ISSUE THREAD

**Issue by ruimarinho** [uphold/github-changelog-generator#14]
We could use the repository URL available on the `package.json` when `github-changelog-generator` is executed to automatically extract the owner and repository information.

### Example:

Running `github-changelog-generator` on a project with the following `package.json`:

```js
{
  "name": "Foo Bar",
  "version": "1.0.0",
  "repository": "git@github.com/uphold/foobar"
}
```

Should be able to set the default value of `--owner` to `uphold` and `--repo` to `foobar`.

**Comment by rplopes** [comment]
Resolved by https://github.com/uphold/github-changelog-generator/pull/50, which fetches the repository owner and name from the project's git config instead of from package.json, which doesn't always have that information, and that information is not always set correctly.
